### ISSUE TITLE
[EPIC] Covering 100% of Kubernetes constructs in Kedge

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#101]
So! We've got quite a task for us ahead in terms of getting a complete YAML Kedge file.

With that being said, we've got to *try* to cover all of Kubernetes in the simplest, possible way. 

Thus, we will need support MOST constructs of Kubernetes in order to achieve that goal. Here's an overview with what I think needs to be implemented, and what doesn't.

I have marked those I believe *have* been implemented with [X], for example, Services and Deployments we currently (and successfully) convert to.

### To implement:

Most common are:                                                                                                                                                                                                                                                                  
 - [X] Deployments - stateless persistent apps (http servers)                                                                                                                                                                                                                     
 - [ ] StatefulSets - stateful persistent apps (databases)                                                                                                                                                                                                                        
 - [x] Jobs - run-to-completion apps (batch jobs) - #52                                                                                                                                                                                                                                  
 - [X] Service - set of Pods with a ClusterIP                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                  
Not-so-common:                                                                                                                                                                                                                                                                    
 - [ ] DaemonSet - ensures that all (or some) nodes run a copy of a Pod                                                                                                                                                                                                           
 - [ ] CronJob - configuration of a single cronjob (this is in ALPHA)                                                                                                                                                                                                             

### To (maybe) not:
                                                                                                                                                                                                                                                                                  
Manually (not typically used by itself):                                                                                                                                                                                                                                                                     
 - [ ] Pod - Collection of containers guaranteed to be located on the node and share resources (should be created through Deployment, Job, StatefulSet).                                                                                                                          
 - [ ] ReplicaSet - Same as rc but has selector support (should be created through Deployment)                                                                                                                                                                                    
 - [ ] ReplicationController - Ensures specific number of pod replicas are running at any given time (should be created through Deployment)                                                                                                                                       
 - [ ] Container - Only created in the context of a Pod (should be created through Pod)

**Comment by kadel** [comment]
> Pod - Collection of containers guaranteed to be located on the node and share resources (should be created through Deployment, Job, StatefulSet).
>  ReplicaSet - Same as rc but has selector support (should be created through Deployment)
>  ReplicationController - Ensures specific number of pod replicas are running at any given time (should be created through Deployment)
>  Container - Only created in the context of a Pod (should be created through Pod)

I don't think we need a way to define any of those separately. Those all low level constructs that are only used by higher level controllers (Deployment, StatefulSet, Job)

**Comment by cdrage** [comment]
@kadel Yup. Hence the "not typically used by itself" comment. We *could* add a manual way of creating the, but ideally, sticking to the higher-level constructs would be the best.
