### ISSUE TITLE
generate openshift artifacts

### ISSUE THREAD

**Issue by surajssd** [kedgeproject/kedge#210]
Right now we only create artifacts which default to kubernetes, but we should also add artifacts for OpenShift as well.

The first thing that comes to my mind is adding a flag similar to kompose called `--provider`. And generating things which are different in OpenShift like `DeploymentConfig`, if we add support for builds in kedge then support for `BuildConfig`.
 
- [x] [Add `--distribution` flag](https://github.com/kedgeproject/kedge/issues/245)
- [x] [Support OpenShift DeploymentConfig](https://github.com/kedgeproject/kedge/issues/237)
- [x] [Support OpenShift Routes](https://github.com/kedgeproject/kedge/issues/238)

**Comment by kadel** [comment]
Let's skip discussions about BuildConfig, that is going to be whole another discussion.

I can see two options how we can add OpenShift support.
First one is adding flag as @surajssd described (i would use `--distribution` as it might be a better name than `--provider` - OpenShift is distribution of Kubernetes)

The second option is to have two binaries. Something like `kedge-k8s` and `kedge-openshift`. Rationale for this is that almost no one is using both. You deploy to plain Kubernetes or to OpenShift, but usually not to both. Then why complicate this by adding another flag that OpenShift users will have to always remember set. This will make it little less complicated for users as all its required is to download a right binary. User  doesn't have to worry about providing right flag.

**Comment by pradeepto** [comment]
@kadel @surajssd Does this issue need to be scoped out better than "generate resources". But what after that? `kedge deploy` should be able to work with `oc` instead of `kubectl`. WDTY?

**Comment by aslakknutsen** [comment]
@kadel One consumer that needs both k8 and os is fabric8. It could download both binaries of course.. but

**Comment by pradeepto** [comment]
Chatted with @aslakknutsen just now. He says that his use case requires DeploymentConfig and Routes.

**Comment by pradeepto** [comment]
Created smaller tasks for `DeploymentConfig` and `Routes` and linked them in the original description.

**Comment by kadel** [comment]
> Created smaller tasks for DeploymentConfig and Routes and linked them in the original description.

The first smaller task should be introducing `--distribution` switch to allow switching between k8s and OpenShift.

**Comment by kadel** [comment]
We also need to support multiple OpenShift versions similarly to #141

**Comment by cdrage** [comment]
Routes have been added now: https://github.com/kedgeproject/kedge/issues/238

Can we close @surajssd ?
