### ISSUE TITLE
General UX/UI/Website update tracking card

### ISSUE THREAD

**Issue by cdrage** [kedgeproject/kedge#268]
A few things!

- [x] Update the website with a clear-forward tutorial
- [x] Increase the amount of examples on the website / main page
- [x] Add colour / spice things up
- [x] General look-over Kedge UX (output to files?)
- [x] Setup syncing of Github docs to gh-pages
- [x] Update second section / paragraph
- [x] Two lines at the top need to be merged

**Comment by cdrage** [comment]
Syncing is setup, and the rest of the tasks are completed. Going to go ahead and close this :+1:
