### ISSUE TITLE
generate a json-schema file

### ISSUE THREAD

**Issue by jstrachan** [kedgeproject/kedge#45]
it'd be nice to generate a json schema file so we can include support for kapp inside tools like this: https://github.com/gorkem/vscode-k8s/ so that we can get automatic completion and validation in VS Code / Che / Eclipse.

I wonder if we maybe need to add a line like:
```
kind: App
```
to make it easier to know what schema to use in the IDE plugin?

**Comment by jstrachan** [comment]
since the schema is gonna change, I'm hoping we can automate the generation of the schema as part of the build from the source - am sure the kubernetes project does something like this for its swagger stuff?

**Comment by surajssd** [comment]
For reference:

- Kubernetes JSON Schemas https://github.com/garethr/kubernetes-json-schema
- OpenShift JSON Schemas https://github.com/garethr/openshift-json-schema
- Tool to create json schema from OpenAPI https://github.com/garethr/openapi2jsonschema
- Writing OpenAPI (fka Swagger) Specification https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-1-introduction/
- OpenAPI Specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
- Validate your Kubernetes configuration files, supports multiple Kubernetes versions https://github.com/garethr/kubeval


We need to figure out how do we create a swagger API or openAPI.

**Comment by pradeepto** [comment]
@surajssd Thanks for recording all the links here. Will be helpful.

**Comment by jstrachan** [comment]
BTW here's the project which we use to generate Java DTOs & JSON Schemas for kubernetes and openshift
https://github.com/fabric8io/kubernetes-model - though its Java centric; there's probably an easier way in golang to go straight from the go code -> json schema

**Comment by surajssd** [comment]
Right now the work is being done in https://github.com/surajssd/kedgeSchema

It can generate the schema but not sure if the schema is complete or correct

**Comment by surajssd** [comment]
removing the image field

```json
$ cat ./example/db.json 
{
  "name": "database",
  "containers": [
    {
      "name": "db",
      "env": [
        {
          "name": "MYSQL_ROOT_PASSWORD",
          "value": "rootpasswd"
        },
        {
          "name": "MYSQL_PASSWORD",
          "value": "wordpress"
        }
      ],
      "envFrom": [
        {
          "configMapRef": {
            "name": "database"
          }
        }
      ]
    }
  ],
...
```
trying to validate

```bash
$ jsonschema -F "{error.message}" -i ./example/db.json ./configs/appspec.json 
u'image' is a required property
```

errors out

---

changing the field type of `name`

```json
$ cat ./example/db.json 
{
  "name": 1,
  "containers": [
    {
...
```

errors out as:

```bash
$ jsonschema -F "{error.message}" -i ./example/db.json ./configs/appspec.json 
1 is not of type u'string'
```

---

The file [configs/appspec.json](https://github.com/surajssd/kedgeSchema/blob/master/configs/appspec.json) is the schema for kedge if I am not mistaken.

**Comment by pradeepto** [comment]
@surajssd This is a great start. We should break this issue into multiple issues and have checklist. WDYT?

**Comment by surajssd** [comment]
>@surajssd This is a great start. We should break this issue into multiple issues and have checklist. WDYT?

Yes I think so we can create a checklist to do that

**Comment by surajssd** [comment]
- [ ] Find the right place to place this jsonschema generation code
- [ ] Put some explanation of how this generation works
- [ ] Everytime we update anything in `spec.go` there has to be a parallel update in the base schema.
- [ ] What K8s version do we base off of?
- [ ] Versioning of the jsonschema

**Comment by kadel** [comment]
could we create new subcommand  for generating current jsonschema?  Something like `kedge jsonschema` that will output json schema to stdout?

**Comment by kadel** [comment]
how will #119  impact Json schema generation?

**Comment by surajssd** [comment]
@kadel not sure how it will impact the jsonschema I wil need to find that because now we won't have one struct but multiple ones, so can't say anything now!

**Comment by pradeepto** [comment]
We need to make sure the generated json schema are stored as artifacts some where in the repository. And this file should be generated by CI for every release for now.

**Comment by surajssd** [comment]
>Find the right place to place this jsonschema generation code

Generation code resides in https://github.com/kedgeproject/kedge-jsonschema

> Put some explanation of how this generation works

The repo has documentation of how to generate the configs, also the way code works can be understood by reading comments in code

> Everytime we update anything in `spec.go` there has to be a parallel update in the base schema

This needs to be done filed an issue for this one https://github.com/kedgeproject/kedge/issues/280

> What K8s version do we base off of?

right now it is based on k8s 1.7 https://github.com/kedgeproject/kedge-jsonschema/blob/master/scripts/k8s-release

> Versioning of the jsonschema

this needs to be evaluated

**Comment by kadel** [comment]
Is there a place where I can find JSON schema for the latest release?

**Comment by surajssd** [comment]
@kadel here:
https://github.com/kedgeproject/json-schema/tree/master/schema
